apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: web-server
spec:
  source-image: ${IMAGE_NAME}
  unprotected_image: ${IMAGE_NAME}
  destination_image: ${DESTINATION_IMAGE_NAME}
  push_scone_image: true
  enforce: ["/app/web-server"]
  scone-version: ${SCONE_RUNTIME_VERSION}
  tee-type: ${TEE_TYPE}
---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: web-server
spec:
  file:
    - "manifest.yaml"
  output-manifest: "manifest.sanitized.yaml"
  cas-endpoint:
    address: ${CAS_NAME}.${CAS_NAMESPACE}
  container-env:
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_VERSION, value: "1"}
  scone-session-env:
    - {name: SCONE_VERSION, value: "1"}
  permissive: true
  spol: true
  tee-type: ${TEE_TYPE}
  scone_enclave: ${SCONE_ENCLAVE}
  scone-version: ${SCONE_RUNTIME_VERSION}
