apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: hello-world-example
spec:
  protected_image: ${NATIVE_IMAGE_NAME}
  unprotected_image: rust:latest
  destination_image: ${DESTINATION_IMAGE_NAME}
  enforce: ["/usr/local/bin/hello-world"]
  push_scone_image: true
  version: ${SCONE_RUNTIME_VERSION}
  scone_runtime_image: ${SCONE_RUNTIME_IMAGE}
  cvm: ${CVM_MODE}
  storage: "manifests/storage.json"
  manifest_env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: hello-world-example
spec:
  version: ${SCONE_RUNTIME_VERSION}
  scone_runtime_image: ${SCONE_RUNTIME_IMAGE}
  trusted_cvm_signer_keys: ${CVM_SIGNING_KEY_FILE}
  file:
    - "manifests/scone.template.yaml"
  output_manifest_file: "manifests/manifest.prod.sanitized.yaml"
  output_session_file: "manifests/manifest.prod.session.yaml"
  cas_address: ${SCONE_CAS_ADDR}
  session_env:
    - {name: SCONE_VERSION, value: "1"}
  manifest_env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "1G"}
  permissive: true
  spol: true
  cvm: ${CVM_MODE}
  scone_enclave: ${SCONE_ENCLAVE}
