apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: netshield
spec:
  source-image: ${CLIENT_IMAGE}
  unprotected_image: ${CLIENT_IMAGE}
  enforce: ["/usr/local/bin/client-rust"]
  push_scone_image: true
  tee-type: ${TEE_TYPE}
  scone-version: ${SCONE_RUNTIME_VERSION}
  container-env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
---
apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: netshield
spec:
  source-image: ${SERVER_IMAGE}
  unprotected_image: ${SERVER_IMAGE}
  enforce: ["/usr/local/bin/server-rust"]
  push_scone_image: true
  tee-type: ${TEE_TYPE}
  scone-version: ${SCONE_RUNTIME_VERSION}
  container-env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: netshield
spec:
  file:
    - "${SCRIPT_DIR}/manifest.yaml"
  output-manifest: "${SCRIPT_DIR}/manifest.prod.sanitized.yaml"
  output-session: "${SCRIPT_DIR}/manifest.prod.session.yaml"
  cas-endpoint:
    address: ${CAS_NAME}.${CAS_NAMESPACE}
  scone-session-env:
    - {name: SCONE_VERSION, value: "1"}
  container-env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
  permissive: true
  spol: true
  tee-type: ${TEE_TYPE}
  scone_enclave: ${SCONE_ENCLAVE}
  access_policy:
    read:
      - ANY
    update:
      - signer: |
          ${SIGNER}
    create_sessions:
      - signer: |
          ${SIGNER}
