environment:
  IMAGE_NAME: registry.scontain.com/k8s-scone-images/go-args-env-file:native
  DESTINATION_IMAGE_NAME: registry.scontain.com/k8s-scone-images/go-args-env-file:protected
  REGISTRY: registry.scontain.com
  IMAGE_PULL_SECRET_NAME: sconeapps
  CAS_ADDRESS: cas.default
  TEE_TYPE: sgx
  SCONE_ENCLAVE: 'false'
  SCONE_RUNTIME_VERSION: 6.1.0-rc.0
  NAMESPACE: default
  SCONE_RUNTIME_IMAGE: registry.scontain.com/sergey/test:scone-deb-pkgs-scone7.0.0-rc-cvm-mode
  CVM_SIGNING_KEY_FILE: /tmp/kbs-signer.pem
