environment:
  IMAGE_NAME: registry.scontain.com/k8s-scone-images/governance:native
  DESTINATION_IMAGE_NAME: registry.scontain.com/k8s-scone-images/governance:protected
  IMAGE_PULL_SECRET_NAME: sconeapps
  SCONE_RUNTIME_VERSION: 7.0.0-alpha.4
  CAS_ADDRESS: cas.default
  TEE_TYPE: sgx
  SCONE_ENCLAVE: 'false'
  REGISTRY: registry.scontain.com
  NAMESPACE: governance-demo
  GOVERNANCE_URL: 'http://127.0.0.1:8000'
  GOVERNANCE_API_TOKEN: 'stand-in-token'
  SCONE_RUNTIME_IMAGE: registry.scontain.com/sergey/test:scone-deb-pkgs-scone7.0.0-rc-cvm-mode
  CVM_SIGNING_KEY_FILE: /tmp/kbs-signer.pem
