environment:
  IMAGE_NAME: registry.scontain.com/cicd/daniel/hello-world:native
  IMAGE_PULL_SECRET_NAME: sconeapps
  SCONE_CAS_ADDR: https://20.22.79.21:8081/
  DESTINATION_IMAGE_NAME: registry.scontain.com/cicd/daniel/hello-world:protected
  CVM_MODE: true
  SCONE_ENCLAVE: true
  REGISTRY: registry.scontain.com
  SCONE_RUNTIME_VERSION: 7.0.0-alpha.4
  NAMESPACE: default
  SCONE_RUNTIME_IMAGE: registry.scontain.com/sergey/test:scone-deb-pkgs-scone7.0.0-rc-cvm-mode
  CVM_SIGNING_KEY_FILE: /tmp/kbs-signer.pem
  REGISTRY_USER: dandax123
  REGISTRY_TOKEN: uP0A4QS33VAwF79jsPxLKW86MQp1OjEzNAk.01.0z1lrpm7r
  DEMO_DIR: /home/daniel/scone-td-build-demos/scripts/demos/../../demos/hello-world/
