apiVersion: scone.cloud/v1
kind: Register
metadata:
  name: go-args-env-file-example
spec:
  source-image: ${DEMO_IMAGE}
  unprotected_image: ${DEMO_IMAGE}
  destination_image: ${DESTINATION_IMAGE_NAME}
  enforce: ["/usr/local/bin/go-args-env-file"]
  push_scone_image: true
  scone-version: ${SCONE_RUNTIME_VERSION}
  tee-type: ${TEE_TYPE}
  container-env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
---
apiVersion: scone.cloud/v1
kind: Apply
metadata:
  name: go-args-env-file-example
spec:
  file:
    - "manifests/manifest.yaml"
  output-manifest: "manifests/manifest.prod.sanitized.yaml"
  output-session: "manifests/manifest.prod.session.yaml"
  cas-endpoint:
    address: ${CAS_NAME}.${CAS_NAMESPACE}
  scone-session-env:
    - {name: SCONE_VERSION, value: "1"}
  container-env:
    - {name: SCONE_VERSION, value: "1"}
    - {name: SCONE_SYSLIBS, value: "1"}
    - {name: SCONE_PRODUCTION, value: "0"}
    - {name: SCONE_HEAP, value: "2G"}
  permissive: true
  spol: false
  tee-type: ${TEE_TYPE}
  scone_enclave: ${SCONE_ENCLAVE}
  access_policy:
    read:
      - ANY
    update:
      - signer: |
          ${SIGNER}
    create_sessions:
      - signer: |
          ${SIGNER}
