environment:
  NATIVE_IMAGE_NAME: registry.scontain.com/k8s-scone-images/configmap:native
  DESTINATION_IMAGE_NAME: registry.scontain.com/workshop/configmap:protected
  IMAGE_PULL_SECRET_NAME: sconeapps
  SCONE_RUNTIME_VERSION: 7.0.0-alpha.4
  SCONE_CAS_ADDR: cas.default
  CVM_MODE: false
  SCONE_ENCLAVE: false
  REGISTRY: registry.scontain.com
  NAMESPACE: default
  SCONE_RUNTIME_IMAGE: registry.scontain.com/sergey/test:scone-deb-pkgs-scone7.0.0-rc-cvm-mode
  CVM_SIGNING_KEY_FILE: /tmp/kbs-signer.pem
