apiVersion: batch/v1
kind: Job
metadata:
  name: image-signing
spec:
  template:
    metadata:
      labels:
        app: image-signing
    spec:
      restartPolicy: OnFailure
      containers:
        - name: image-signing
          image: registry.scontain.com/k8s-scone-images/image-signing:native
          imagePullPolicy: Always
      imagePullSecrets:
        - name: sconeapps
  backoffLimit: 4
