environment:
  IMAGE_PULL_SECRET_NAME: sconeapps
  SCONE_CAS_ADDR: cas.default
  SCONE_RUNTIME_VERSION: 7.0.0-alpha.4
  CVM_MODE: false
  SCONE_ENCLAVE: false
  REGISTRY: registry.scontain.com
  NAMESPACE: default
  CLIENT_IMAGE: registry.scontain.com/workshop/network-policy:client
  SERVER_IMAGE: registry.scontain.com/workshop/network-policy:server
  SCRIPT_DIR: .
  SIGNER: |-
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAvSRST+dhEaX42c6VkY1Sv+KVelnSup96M6TMHOlqcrg=
    -----END PUBLIC KEY-----
