#!/usr/bin/env bash
# Generated file. Do not edit manually.

set -Eeuo pipefail

TYPE_SPEED="${TYPE_SPEED:-25}"
PAUSE_AFTER_CMD="${PAUSE_AFTER_CMD:-0.6}"
SHELLRC="${SHELLRC:-/dev/null}"
PROMPT="${PROMPT:-$'\[\e[1;32m\]demo\[\e[0m\]:\[\e[1;34m\]~\[\e[0m\]\$ '}"
COLUMNS="${COLUMNS:-100}"
LINES="${LINES:-26}"
ORANGE="${ORANGE:-\033[38;5;208m}"
LILAC="${LILAC:-\033[38;5;141m}"
RESET="${RESET:-\033[0m}"

slow_type() {
  local text="$*"
  local delay
  delay=$(awk "BEGIN { print 1 / $TYPE_SPEED }")
  for ((i=0; i<${#text}; i++)); do
    printf "%s" "${text:i:1}"
    sleep "$delay"
  done
}

pe() {
  local cmd="$*"
  printf "%b" "$ORANGE"
  slow_type "$cmd"
  printf "%b" "$RESET"
  printf "\n"

  if [[ -n "${PE_BUFFER:-}" ]]; then
    PE_BUFFER+=$'\n'
  fi
  PE_BUFFER+="$cmd"

  # Execute only when buffered lines form a complete shell command.
  if bash -n <(printf '%s\n' "$PE_BUFFER") 2>/dev/null; then
    eval "$PE_BUFFER"
    PE_BUFFER=""
  fi

  sleep "$PAUSE_AFTER_CMD"
}

export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export COLUMNS LINES
export PS1="$PROMPT"
stty cols "$COLUMNS" rows "$LINES"

show_help() {
  cat <<USAGE
Usage: $0 [--help] [--non-interactive]

Runs a demo-style shell script generated from demos/software-updates/README.md.

Options:
  --help             Show this help message and exit.
  --non-interactive  Do not force confirmation for existing tplenv values.
USAGE
}

NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      show_help
      exit 0
      ;;
    --non-interactive)
      NON_INTERACTIVE=true
      unset CONFIRM_ALL_ENVIRONMENT_VARIABLES || true
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Error: Unknown option '$1'." >&2
      show_help >&2
      exit 1
      ;;
    *)
      echo "Error: This script does not accept positional arguments." >&2
      show_help >&2
      exit 1
      ;;
  esac
done

if [[ $# -gt 0 ]]; then
  echo "Error: This script does not accept positional arguments." >&2
  show_help >&2
  exit 1
fi

unset CONFIRM_ALL_ENVIRONMENT_VARIABLES || true

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Directory of the README this script was generated from. The README
# code blocks use it for every file reference so the script works from
# any working directory.
export DEMO_DIR="$(cd "${script_dir}/../demos/software-updates" && pwd)"

printf "%b" "$LILAC"
printf '%s\n' '# Software Updates for Confidential Python Applications'
printf '%s\n' ''
printf '%s\n' 'This example demonstrates how to perform a **software update** of a confidential Python application using SCONE and `scone-td-build`. Two versions of the application are built and deployed as a Kubernetes Deployment:'
printf '%s\n' ''
printf '%s\n' '- **Version 1** — the initial deployment, running in a loop that continuously verifies `API_PASSWORD`'
printf '%s\n' '- **Version 2** — the updated version, replacing Version 1 via a Kubernetes rolling update'
printf '%s\n' ''
printf '%s\n' 'The key point of the demo: `API_PASSWORD` is **generated by CAS** on first session creation via a `SconeSecret` — nobody sets it, not even the cluster admin. It lives only inside the enclave. After the software update, Version 2 receives the **same CAS-generated password** (CAS auto-migrates `ascii` secrets when a session is updated under the same namespace), and the application actively verifies this by comparing checksums.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Project Structure'
printf '%s\n' ''
printf '%s\n' 'demos/software-updates/'
printf '%s\n' '├── app/'
printf '%s\n' '│   ├── print_env1.py              # Version 1: prints checksum, loops every 10s'
printf '%s\n' '│   ├── print_env2.py              # Version 2: same loop, different greeting'
printf '%s\n' '│   └── Dockerfile                 # Builds either version via --build-arg VERSION=1|2'
printf '%s\n' '├── manifests/'
printf '%s\n' '│   ├── manifest.v1.template.yaml  # Kubernetes Deployment template for Version 1'
printf '%s\n' '│   ├── manifest.v2.template.yaml  # Kubernetes Deployment template for Version 2'
printf '%s\n' '│   ├── scone.v1.template.yaml     # SCONE Register + Apply template for Version 1'
printf '%s\n' '│   ├── scone.v2.template.yaml     # SCONE Register + Apply template for Version 2'
printf '%s\n' '│   └── scone-secret.yaml          # SconeSecret: CAS generates API_PASSWORD'
printf '%s\n' '├── values.template.yaml           # default values, copied to Values.yaml on first run'
printf '%s\n' '└── README.md'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Prerequisites'
printf '%s\n' ''
printf '%s\n' '- A token for accessing `scone.cloud` images on `registry.scontain.com`'
printf '%s\n' '- A Kubernetes cluster with SGX or CVM support'
printf '%s\n' '- The Kubernetes command-line tool (`kubectl`)'
printf '%s\n' '- Rust `cargo` (`curl --proto '\''=https'\'' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)'
printf '%s\n' '- `tplenv` (`cargo install tplenv`) and `retry-spinner` (`cargo install retry-spinner`)'
printf '%s\n' '- `docker` with push access to a registry your cluster can pull from'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 1. Set Up the Environment'
printf '%s\n' ''
printf '%s\n' 'Every file reference below goes through `$DEMO_DIR`, this demo'\''s directory. The generated scripts set it for you; when following this README by hand, run the commands from this directory. Then clean up state left over from a previous run:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# The generated scripts set DEMO_DIR to this demo's directory. When following
EOF
)"
pe "$(cat <<'EOF'
# this README by hand, run the commands from `demos/software-updates`.
EOF
)"
pe "$(cat <<'EOF'
export DEMO_DIR="${DEMO_DIR:-$PWD}"
EOF
)"
pe "$(cat <<'EOF'
# Remove generated state files from any previous run.
EOF
)"
pe "$(cat <<'EOF'
rm -f "$DEMO_DIR/manifests/storage.json" "$DEMO_DIR/manifests/scone.v1.yaml" "$DEMO_DIR/manifests/scone.v2.yaml" "$DEMO_DIR/manifests/manifest.v1.yaml" "$DEMO_DIR/manifests/manifest.v2.yaml" "$DEMO_DIR/manifests/manifest.prod.sanitized.yaml" "$DEMO_DIR/manifests/manifest.prod.session.yaml" || true
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'Load the full variable set from `environment-variables.md` first, so `NAMESPACE` and'
printf '%s\n' '`CVM_MODE` are available to derive the CAS session namespace below. Default values live in `$DEMO_DIR/values.template.yaml`; copy it to `Values.yaml` if that file does not already exist:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Seed Values.yaml from the template on first run only.
EOF
)"
pe "$(cat <<'EOF'
[ -f "$DEMO_DIR/Values.yaml" ] || cp "$DEMO_DIR/values.template.yaml" "$DEMO_DIR/Values.yaml"
EOF
)"
pe "$(cat <<'EOF'
# Load environment variables from the tplenv definition file.
EOF
)"
pe "$(cat <<'EOF'
eval $(tplenv --file "$DEMO_DIR/../environment-variables.md" --create-values-file --values-file "$DEMO_DIR/Values.yaml"  --context --eval --eval-export-values ${CONFIRM_ALL_ENVIRONMENT_VARIABLES-} --output /dev/null)
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'Set `SIGNER` for policy signing and the CAS session namespace shared by both v1 and v2 builds:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Export the required environment variable for the next steps.
EOF
)"
pe "$(cat <<'EOF'
export SIGNER="$(scone self show-session-signing-key)"
EOF
)"
pe "$(cat <<'EOF'
# Fixed per Kubernetes NAMESPACE and CVM_MODE on purpose: CAS sessions are append-only
EOF
)"
pe "$(cat <<'EOF'
# (there's no delete operation in the CLI), so a fresh random namespace on every run
EOF
)"
pe "$(cat <<'EOF'
# would leave a new, never-cleaned-up session behind each time. Reusing the same name
EOF
)"
pe "$(cat <<'EOF'
# for repeat runs of the *same* NAMESPACE and mode means a rerun updates the existing
EOF
)"
pe "$(cat <<'EOF'
# session in place (the same mechanism Part 2's v1 -> v2 update already relies on)
EOF
)"
pe "$(cat <<'EOF'
# instead of accumulating one per run. Including NAMESPACE and the mode keeps that
EOF
)"
pe "$(cat <<'EOF'
# property while still isolating different Kubernetes namespaces (different users,
EOF
)"
pe "$(cat <<'EOF'
# different environments) and the SGX vs CVM CI sweeps from sharing one CAS session
EOF
)"
pe "$(cat <<'EOF'
# and one generated API_PASSWORD.
EOF
)"
pe "$(cat <<'EOF'
mode_suffix="sgx"
EOF
)"
pe "$(cat <<'EOF'
if [ "${CVM_MODE}" = "true" ]; then
EOF
)"
pe "$(cat <<'EOF'
  mode_suffix="cvm"
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
export SESSION_NAMESPACE="software-update-demo-${NAMESPACE}-${mode_suffix}"
EOF
)"
pe "$(cat <<'EOF'
# Print a status message.
EOF
)"
pe "$(cat <<'EOF'
echo "SESSION_NAMESPACE=${SESSION_NAMESPACE}"
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 2. Build and Push the Native Docker Images'
printf '%s\n' ''
printf '%s\n' 'The Dockerfile accepts a `VERSION` build argument to choose which Python script to embed. Build both versions:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Build the Version 1 container image.
EOF
)"
pe "$(cat <<'EOF'
docker build --build-arg VERSION=1 -t ${IMAGE_NAME_V1} "$DEMO_DIR/app"
EOF
)"
pe "$(cat <<'EOF'
# Push the Version 1 container image to the registry.
EOF
)"
pe "$(cat <<'EOF'
docker push ${IMAGE_NAME_V1}
EOF
)"
pe "$(cat <<'EOF'
# Build the Version 2 container image.
EOF
)"
pe "$(cat <<'EOF'
docker build --build-arg VERSION=2 -t ${IMAGE_NAME_V2} "$DEMO_DIR/app"
EOF
)"
pe "$(cat <<'EOF'
# Push the Version 2 container image to the registry.
EOF
)"
pe "$(cat <<'EOF'
docker push ${IMAGE_NAME_V2}
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 3. Create the Kubernetes Namespace'
printf '%s\n' ''
printf '%s\n' 'We try to ensure the namespace exists. This may fail when running in a container already in the target namespace, so we ignore that failure.'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Create the Kubernetes namespace if it does not already exist.
EOF
)"
pe "$(cat <<'EOF'
kubectl create namespace ${NAMESPACE} --dry-run=client -o yaml | kubectl apply -f - 2> /dev/null || echo "Patching namespace ${NAMESPACE} failed -- ignoring this"
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 4. Add a Docker Registry Secret'
printf '%s\n' ''
printf '%s\n' 'A pull secret is needed to pull the confidential container images.'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Check whether the pull secret already exists.
EOF
)"
pe "$(cat <<'EOF'
if kubectl get secret -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" >/dev/null 2>&1; then
EOF
)"
pe "$(cat <<'EOF'
  # Print a status message.
EOF
)"
pe "$(cat <<'EOF'
  echo "Secret ${IMAGE_PULL_SECRET_NAME} already exists"
EOF
)"
pe "$(cat <<'EOF'
else
EOF
)"
pe "$(cat <<'EOF'
  # Print a status message.
EOF
)"
pe "$(cat <<'EOF'
  echo "Secret ${IMAGE_PULL_SECRET_NAME} does not exist - creating now."
EOF
)"
pe "$(cat <<'EOF'
  # Create the Docker registry pull secret.
EOF
)"
pe "$(cat <<'EOF'
  kubectl create secret docker-registry -n "${NAMESPACE}" "${IMAGE_PULL_SECRET_NAME}" --docker-server=$REGISTRY --docker-username=$REGISTRY_USER --docker-password=$REGISTRY_TOKEN
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## 5. Render the Manifests'
printf '%s\n' ''
printf '%s\n' 'Render the Kubernetes deployment manifests and SCONE configurations for both versions:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Render the Version 1 SCONE configuration.
EOF
)"
pe "$(cat <<'EOF'
tplenv --file "$DEMO_DIR/manifests/scone.v1.template.yaml" --values-file "$DEMO_DIR/Values.yaml" --create-values-file --output "$DEMO_DIR/manifests/scone.v1.yaml" --indent
EOF
)"
pe "$(cat <<'EOF'
# Render the Version 2 SCONE configuration.
EOF
)"
pe "$(cat <<'EOF'
tplenv --file "$DEMO_DIR/manifests/scone.v2.template.yaml" --values-file "$DEMO_DIR/Values.yaml" --create-values-file --output "$DEMO_DIR/manifests/scone.v2.yaml" --indent
EOF
)"
pe "$(cat <<'EOF'
# Render the Version 1 Kubernetes manifest.
EOF
)"
pe "$(cat <<'EOF'
tplenv --file "$DEMO_DIR/manifests/manifest.v1.template.yaml" --values-file "$DEMO_DIR/Values.yaml" --create-values-file --output "$DEMO_DIR/manifests/manifest.v1.yaml" --indent
EOF
)"
pe "$(cat <<'EOF'
# Render the Version 2 Kubernetes manifest.
EOF
)"
pe "$(cat <<'EOF'
tplenv --file "$DEMO_DIR/manifests/manifest.v2.template.yaml" --values-file "$DEMO_DIR/Values.yaml" --create-values-file --output "$DEMO_DIR/manifests/manifest.v2.yaml" --indent
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Part 1 — Deploy Version 1 (SCONE)'
printf '%s\n' ''
printf '%s\n' 'In the SCONE deployment, `API_PASSWORD` is **generated by CAS** via `manifests/scone-secret.yaml`. Nobody sets it — CAS creates it when the session is first applied and injects it into the enclave at runtime. It never appears in any Kubernetes manifest or Secret visible to a cluster administrator.'
printf '%s\n' ''
printf '%s\n' '### Step 6. Generate the signing key'
printf '%s\n' ''
printf '%s\n' 'When protecting binaries for confidential execution, `scone-td-build` signs them with a key stored in `identity.pem`:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Check whether the signing key needs to be generated.
EOF
)"
pe "$(cat <<'EOF'
if [ ! -f "$DEMO_DIR/identity.pem" ]; then
EOF
)"
pe "$(cat <<'EOF'
  # Print a status message.
EOF
)"
pe "$(cat <<'EOF'
  echo "Generating identity.pem ..."
EOF
)"
pe "$(cat <<'EOF'
  # Generate the signing key for confidential binaries.
EOF
)"
pe "$(cat <<'EOF'
  openssl genrsa -3 -out "$DEMO_DIR/identity.pem" 3072
EOF
)"
pe "$(cat <<'EOF'
else
EOF
)"
pe "$(cat <<'EOF'
  # Print a status message.
EOF
)"
pe "$(cat <<'EOF'
  echo "identity.pem already exists."
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '### Step 7. Build the confidential image and session for Version 1'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Remove any existing state file.
EOF
)"
pe "$(cat <<'EOF'
rm -f "$DEMO_DIR/manifests/storage.json" || true
EOF
)"
pe "$(cat <<'EOF'
# Generate the confidential image and sanitized manifest from the SCONE configuration.
EOF
)"
pe "$(cat <<'EOF'
(cd "$DEMO_DIR" && scone-td-build from -y manifests/scone.v1.yaml)
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'This command:'
printf '%s\n' ''
printf '%s\n' '- Registers and pushes the Version 1 confidential image (`${DESTINATION_IMAGE_NAME_V1}`)'
printf '%s\n' '- Creates a CAS session under namespace `${SESSION_NAMESPACE}` with a `SconeSecret` that tells CAS to generate `API_PASSWORD`'
printf '%s\n' '- Produces `$DEMO_DIR/manifests/manifest.prod.sanitized.yaml` referencing the confidential image — `API_PASSWORD` does not appear in it'
printf '%s\n' ''
printf '%s\n' '### Step 8. Deploy Version 1 (SCONE)'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Apply the Kubernetes manifest.
EOF
)"
pe "$(cat <<'EOF'
kubectl apply -f "$DEMO_DIR/manifests/manifest.prod.sanitized.yaml" --namespace ${NAMESPACE}
EOF
)"
pe "$(cat <<'EOF'
# Wait for the deployment rollout to complete.
EOF
)"
pe "$(cat <<'EOF'
kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '### Step 9. Verify the Version 1 deployment'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Show the most recent logs and capture the Version 1 API_PASSWORD checksum, so Step 12
EOF
)"
pe "$(cat <<'EOF'
# can check it against Version 2's automatically instead of relying on a human comparing
EOF
)"
pe "$(cat <<'EOF'
# two printed checksums by eye.
EOF
)"
pe "$(cat <<'EOF'
# The SCONE runtime prints its enclave banner several seconds before the Python app's
EOF
)"
pe "$(cat <<'EOF'
# first line, and `kubectl logs` exits 0 as soon as that banner exists -- so retrying on
EOF
)"
pe "$(cat <<'EOF'
# its exit code captures the logs before the app has printed anything. Poll for the app's
EOF
)"
pe "$(cat <<'EOF'
# own checksum line instead.
EOF
)"
pe "$(cat <<'EOF'
v1_log=""
EOF
)"
pe "$(cat <<'EOF'
for _ in $(seq 1 30); do v1_log=$(kubectl logs -n ${NAMESPACE} deployment/python-hello-user 2>/dev/null || true); echo "$v1_log" | grep -q "checksum of the original API_PASSWORD" && break; sleep 5; done
EOF
)"
pe "$(cat <<'EOF'
echo "$v1_log" | tail -10
EOF
)"
pe "$(cat <<'EOF'
v1_checksum=$(echo "$v1_log" | grep -m1 "checksum of the original API_PASSWORD" | grep -oE "'[^']+'" | tr -d "'")
EOF
)"
pe "$(cat <<'EOF'
if [ -z "$v1_checksum" ]; then
EOF
)"
pe "$(cat <<'EOF'
  echo "Could not find the Version 1 API_PASSWORD checksum in the logs" >&2
EOF
)"
pe "$(cat <<'EOF'
  exit 1
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
echo "Version 1 API_PASSWORD checksum: ${v1_checksum}"
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'You should see output repeating every 10 seconds:'
printf '%s\n' ''
printf '%s\n' 'Version 1: Hello, '\''myself'\'' - thanks for passing along the API_PASSWORD'
printf '%s\n' 'The checksum of the original API_PASSWORD is '\''<checksum>'\'''
printf '%s\n' 'Hello, user '\''myself'\''!'
printf '%s\n' 'The checksum of the current password is '\''<checksum>'\'''
printf '%s\n' 'Running Version 1. Update by applying the v2 confidential manifest.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Part 2 — Software Update to Version 2'
printf '%s\n' ''
printf '%s\n' '`API_PASSWORD` is **not modified** during this update. Both v1 and v2 Apply CRDs share the same `SESSION_NAMESPACE`, so `scone-td-build` updates the existing CAS session rather than creating a new one. CAS auto-migrates `ascii` secrets on session update, preserving the same generated value.'
printf '%s\n' ''
printf '%s\n' '### Step 10. Build the confidential image and update the session for Version 2'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Generate the confidential image and sanitized manifest from the SCONE configuration.
EOF
)"
pe "$(cat <<'EOF'
(cd "$DEMO_DIR" && scone-td-build from -y manifests/scone.v2.yaml)
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'This command:'
printf '%s\n' ''
printf '%s\n' '- Registers and pushes the Version 2 confidential image (`${DESTINATION_IMAGE_NAME_V2}`)'
printf '%s\n' '- Updates the existing CAS session (same `SESSION_NAMESPACE` as Version 1) — CAS preserves `API_PASSWORD`'
printf '%s\n' '- Produces `$DEMO_DIR/manifests/manifest.prod.sanitized.yaml` referencing the Version 2 confidential image'
printf '%s\n' ''
printf '%s\n' '### Step 11. Apply the rolling update'
printf '%s\n' ''
printf '%s\n' 'Applying the new manifest triggers a Kubernetes rolling update — Version 1 pods are replaced by Version 2 pods without downtime:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Apply the updated Kubernetes manifest.
EOF
)"
pe "$(cat <<'EOF'
kubectl apply -f "$DEMO_DIR/manifests/manifest.prod.sanitized.yaml" --namespace ${NAMESPACE}
EOF
)"
pe "$(cat <<'EOF'
# Wait for the rolling update to complete.
EOF
)"
pe "$(cat <<'EOF'
kubectl rollout status deployment/python-hello-user -n ${NAMESPACE} --timeout=300s
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' '### Step 12. Verify the Version 2 deployment'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Show the most recent logs from Version 2 and check its API_PASSWORD checksum against
EOF
)"
pe "$(cat <<'EOF'
# Version 1's captured in Step 9. This is the actual cross-version check: each program
EOF
)"
pe "$(cat <<'EOF'
# only ever compares against its own startup value, so without this the demo would pass
EOF
)"
pe "$(cat <<'EOF'
# even if CAS had regenerated API_PASSWORD during the update.
EOF
)"
pe "$(cat <<'EOF'
# Same enclave-banner race as Step 9: poll until the Version 2 app loop is actually
EOF
)"
pe "$(cat <<'EOF'
# printing, otherwise the "Running Version 2." check below races the enclave start.
EOF
)"
pe "$(cat <<'EOF'
v2_log=""
EOF
)"
pe "$(cat <<'EOF'
for _ in $(seq 1 30); do v2_log=$(kubectl logs -n ${NAMESPACE} deployment/python-hello-user 2>/dev/null || true); echo "$v2_log" | grep -q "Running Version 2\." && break; sleep 5; done
EOF
)"
pe "$(cat <<'EOF'
echo "$v2_log" | tail -10
EOF
)"
pe "$(cat <<'EOF'
# Prove Version 2 is actually the program running, not just that the checksum matched.
EOF
)"
pe "$(cat <<'EOF'
# Both programs print an identical checksum line, so a stale Version 1 deployment (or a
EOF
)"
pe "$(cat <<'EOF'
# no-op rollout) would satisfy that check alone as long as the password never changed.
EOF
)"
pe "$(cat <<'EOF'
if ! echo "$v2_log" | grep -q "Running Version 2\."; then
EOF
)"
pe "$(cat <<'EOF'
  echo "Did not find the Version 2 marker in the logs; Version 1 may still be running" >&2
EOF
)"
pe "$(cat <<'EOF'
  exit 1
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
if echo "$v2_log" | grep -q "Running Version 1\."; then
EOF
)"
pe "$(cat <<'EOF'
  echo "Found a Version 1 marker in the logs; the rollout may not have replaced all pods" >&2
EOF
)"
pe "$(cat <<'EOF'
  exit 1
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
v2_checksum=$(echo "$v2_log" | grep -m1 "checksum of the original API_PASSWORD" | grep -oE "'[^']+'" | tr -d "'")
EOF
)"
pe "$(cat <<'EOF'
if [ -z "$v2_checksum" ]; then
EOF
)"
pe "$(cat <<'EOF'
  echo "Could not find the Version 2 API_PASSWORD checksum in the logs" >&2
EOF
)"
pe "$(cat <<'EOF'
  exit 1
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
if [ "$v2_checksum" != "$v1_checksum" ]; then
EOF
)"
pe "$(cat <<'EOF'
  echo "API_PASSWORD checksum changed across the update: Version 1 was '${v1_checksum}', Version 2 is '${v2_checksum}'" >&2
EOF
)"
pe "$(cat <<'EOF'
  exit 1
EOF
)"
pe "$(cat <<'EOF'
fi
EOF
)"
pe "$(cat <<'EOF'
echo "API_PASSWORD checksum verified unchanged across the update: ${v2_checksum}"
EOF
)"
pe "$(cat <<'EOF'
echo "Confirmed Version 2 is the program actually running."
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'You should see output such as:'
printf '%s\n' ''
printf '%s\n' 'Version 2 (updated): Hello, '\''myself'\'' - software update successful!'
printf '%s\n' 'The checksum of the original API_PASSWORD is '\''<checksum>'\'''
printf '%s\n' 'Hello, user '\''myself'\''!'
printf '%s\n' 'The checksum of the current password is '\''<checksum>'\'''
printf '%s\n' 'Running Version 2.'
printf '%s\n' ''
printf '%s\n' 'The script above already verified the checksum matches the one captured from Version 1, confirming that `API_PASSWORD` was generated by CAS once and preserved across the software update.'
printf '%s\n' ''
printf '%s\n' '---'
printf '%s\n' ''
printf '%s\n' '## Cleanup'
printf '%s\n' ''
printf '%s\n' 'Remove the deployed Kubernetes resources when you are finished:'
printf '%s\n' ''
printf "%b" "$RESET"

pe "$(cat <<'EOF'
# Delete the Kubernetes deployment.
EOF
)"
pe "$(cat <<'EOF'
kubectl delete deployment python-hello-user --namespace ${NAMESPACE} --ignore-not-found
EOF
)"

printf "%b" "$LILAC"
printf '%s\n' ''
printf '%s\n' 'This does not, and cannot, delete the CAS-side session under `${SESSION_NAMESPACE}`: CAS'
printf '%s\n' 'sessions are append-only and the `scone` CLI has no session-delete operation, by design,'
printf '%s\n' 'so the audit trail of every update stays intact. Since `${SESSION_NAMESPACE}` is fixed'
printf '%s\n' 'per `NAMESPACE`/mode (see Step 1), re-running this demo later with the same `NAMESPACE`'
printf '%s\n' 'and `CVM_MODE` updates that same session in place instead of leaving a new one behind, so'
printf '%s\n' 'there'\''s no unbounded buildup of sessions or generated `API_PASSWORD` values across runs.'
printf '%s\n' 'Different namespaces or modes (including the SGX and CVM CI sweeps) each get their own'
printf '%s\n' 'isolated session instead of sharing one.'
printf "%b" "$RESET"

